project_id = "wdgpmpgdlauiawbtbxmn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-2fa-code]
verify_jwt = false

[functions.send-new-device-notification]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.verify-password-reset]
verify_jwt = false

[functions.send-signup-verification]
verify_jwt = false

[functions.verify-signup-code]
verify_jwt = false

[functions.download-team-emblems]
verify_jwt = false

[functions.send-delete-account-code]
verify_jwt = false

[functions.scrape-teams]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.clear-expired-bans]
verify_jwt = false

[functions.notify-support-response]
verify_jwt = false
